### ISSUE TITLE
Tensorflow Integration

### ISSUE THREAD

**Issue by ianpotpie** [jmschrei/avocado#17]
It looks like Tensorflow is not listed as a package requirement, although the package will fail to run without it. Additionally, if tensorflow is installed, line 23 in models.py throws an error about Adam not being in the keras package.

I commented out the Adam line and once I did it ran without errors. However, I run out of memory when trying to impute some histone data. Specifically, it fails to set batch data. I am not sure why this is happening since I am not training a new model.

**Comment by jmschrei** [comment]
Avocado does not require tensorflow. Because this project started a long time ago, all of my research code used theano as Keras's backend. Keras is fairly modular such that you can swap in TensorFlow with only minimal changes, as you've noted, but you don't need it.

**Comment by ekinda** [comment]
3 years late, but I had a related issue where keras defaults to tensorflow and required it to import avocado. For me the solution was to do

```
import os
os.environ['KERAS_BACKEND'] = 'theano'
from avocado import Avocado
```
