### ISSUE TITLE
Can't find "Input" function in building model

### ISSUE THREAD

**Issue by KailiBio** [jmschrei/avocado#8]
Hi Jacob! I am trying to build an avocado model using my own data. But I couldn't find the definitione of function "Input" which used in "build_model".

**Comment by jmschrei** [comment]
Howdy!

I'm not sure what you mean. The `Input` layer is a standard layer in Keras. The value that should be input is the index of either the biosample (cell type), assay, or genomic locus, depending on which axis you are inputting a value for. Can you give a few more details on what you're confused by?

**Comment by KailiBio** [comment]
I am trying to build my own model. 
So I use the build_model function in DEMO, like
`MyAvocado = build_model(n_celltypes=11, n_celltype_factors=32, n_assays=11, n_assay_factors=256,
    n_genomic_positions=2328192, n_25bp_factors=25, n_250bp_factors=40, n_5kbp_factors=45,
    n_layers=2, n_nodes=2048, freeze_celltypes=False, freeze_assays=False,
    freeze_genome_25bp=False, freeze_genome_250bp=False,
    freeze_genome_5kbp=False, freeze_network=False)`
I only change the n_celltype, n_assay, and n_genomic_positions, others are default.

But I got an error:
"celltype_input` = Input(shape=(1,), name="celltype_input")
NameError: global name 'Input' is not defined".

**Comment by jmschrei** [comment]
Oh, I see. Are you bringing to imports with you? The imports from keras should be at the top of the `model.py` file.

**Comment by KailiBio** [comment]
It works now. Thank you! :)
